spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bootex
    username: bootuser
    password: bootuser
    thymeleaf:
      cache: false
  servlet:
    multipart:
      enabled: true
      location: "E:/spring/goocodan/upload/"
      max-request-size: 30MB
      max-file-size: 10MB

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    database: mysql

custom:
  upload:
    path: "E:/spring/goocodan/upload/"
